### ISSUE TITLE
Weird behaviour of RGDB with Realsense D435 data in ROS

### ISSUE THREAD

**Issue by diegomrt** [JdeRobot/slam-SD-SLAM#14]
Hi,

I've been testing both mono and RGBD SDSLAM with data from a new Intel Realsense D435 RGBD camera, using ROS. While mono-SLAM goes relatively well, the RGBD version gives a weird output, throwing huge pose values. Please have a look at it in [this video (0:00 mono, 1:15 RGBD)](https://youtu.be/vSqs26TFMOk) . 

Rosbags were recorded at 1280x720, 30 FPS. The D435 was previously calibrated, and the following image topics were added to the .yaml file:

- RGB image raw topic : `/camera/color/image_raw`
- Registered depth image raw topic: `/camera/aligned_depth_to_color/image_raw`

If you need to have a look at the DepthCloud, there is a video [here](https://urjc-my.sharepoint.com/:v:/g/personal/diego_martin_martin_urjc_es/EQFJxnDfPbVPvw5cYAuRKcIBYMFT4L-5mptc6g7-GI9O8g?e=epmUOa). Also, the original rosbag is available for download [here](https://urjc-my.sharepoint.com/:u:/g/personal/diego_martin_martin_urjc_es/EUqJuxBePkBGpkfUrdLL13wBGVK-h-rUCSlK_DmBTPwPRA?e=hJP8ws).  

I've recorded some other rosbags and the behaviour is the same. If you need any of them, please let me know.

**Comment by javimdr** [comment]
Hi Diego,

The problem is that Intel Realsense D435 saves the depth information in millimeters scale instead of meters (as you can read in this [post](https://github.com/IntelRealSense/librealsense/wiki/Projection-in-RealSense-SDK-2.0#depth-image-formats)). Therefore, it is necessary to scale the depth information.

Fortunately, SDSLAM scales the depth image in the "Tracking" module based on `DepthMapFactor` argument as `1 / DepthMapFactor`. This argument can be defined on YAML file, so just add the following line into the file:

- `DepthMapFactor: 1000`

**Comment by diegomrt** [comment]
Hi Javi.

I've just tested it with the same rosbags and it worked flawlessly! There are a couple of videos showing the new results [here](https://urjc-my.sharepoint.com/:f:/g/personal/diego_martin_martin_urjc_es/EkCFYTJYFVlGrlqxOUp9ikwBhGsA-WGU-D68J8pvvlwDlA?e=XnFxFL). In both indoor recordings the RGBD SDSLAM now performs pretty well.

Problem solved. Let's close this issue.
